package com.infamous.dungeons_gear.registry;

import com.infamous.dungeons_gear.enchantments.armor.chest.*;
import com.infamous.dungeons_gear.enchantments.armor.feet.*;
import com.infamous.dungeons_gear.enchantments.armor.head.*;
import com.infamous.dungeons_gear.enchantments.armor.legs.*;
import com.infamous.dungeons_gear.enchantments.melee.*;
import com.infamous.dungeons_gear.enchantments.melee_ranged.*;
import com.infamous.dungeons_gear.enchantments.ranged.*;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static com.infamous.dungeons_gear.DungeonsGear.MODID;

public class EnchantmentInit {
    public static final DeferredRegister<Enchantment> ENCHANTMENTS = DeferredRegister.create(ForgeRegistries.ENCHANTMENTS, MODID);

    public static RegistryObject<AnimaConduitEnchantment> ANIMA_CONDUIT = ENCHANTMENTS.register("anima_conduit", () -> new AnimaConduitEnchantment());
    public static RegistryObject<EnigmaResonatorEnchantment> ENIGMA_RESONATOR = ENCHANTMENTS.register("enigma_resonator", () -> new EnigmaResonatorEnchantment());
    public static RegistryObject<FreezingEnchantment> FREEZING = ENCHANTMENTS.register("freezing", () -> new FreezingEnchantment());
    public static RegistryObject<GravityEnchantment> GRAVITY = ENCHANTMENTS.register("gravity", () -> new GravityEnchantment());
    public static RegistryObject<PoisonCloudEnchantment> POISON_CLOUD = ENCHANTMENTS.register("poison_cloud", () -> new PoisonCloudEnchantment());
    public static RegistryObject<DynamoEnchantment> DYNAMO = ENCHANTMENTS.register("dynamo", () -> new DynamoEnchantment());
    public static RegistryObject<RefreshmentEnchantment> REFRESHMENT = ENCHANTMENTS.register("refreshment", () -> new RefreshmentEnchantment());
    public static RegistryObject<MastersCallEnchantment> MASTERS_CALL = ENCHANTMENTS.register("masters_call", () -> new MastersCallEnchantment());
    public static RegistryObject<ArtifactSynergyEnchantment> ARTIFACT_SYNERGY = ENCHANTMENTS.register("artifact_synergy", () -> new ArtifactSynergyEnchantment());
    public static RegistryObject<BusyBeeEnchantment> BUSY_BEE = ENCHANTMENTS.register("busy_bee", () -> new BusyBeeEnchantment());
    public static RegistryObject<ChainsEnchantment> CHAINS = ENCHANTMENTS.register("chains", () -> new ChainsEnchantment());
    public static RegistryObject<CommittedEnchantment> COMMITTED = ENCHANTMENTS.register("committed", () -> new CommittedEnchantment());
    public static RegistryObject<CriticalHitEnchantment> CRITICAL_HIT = ENCHANTMENTS.register("critical_hit", () -> new CriticalHitEnchantment());
    public static RegistryObject<EchoEnchantment> ECHO = ENCHANTMENTS.register("echo", () -> new EchoEnchantment());
    public static RegistryObject<ExplodingEnchantment> EXPLODING = ENCHANTMENTS.register("exploding", () -> new ExplodingEnchantment());
    public static RegistryObject<GuardingStrikeEnchantment> GUARDING_STRIKE = ENCHANTMENTS.register("guarding_strike", () -> new GuardingStrikeEnchantment());
    public static RegistryObject<IllagersBaneEnchantment> ILLAGERS_BANE = ENCHANTMENTS.register("illagers_bane", () -> new IllagersBaneEnchantment());
    public static RegistryObject<LeechingEnchantment> LEECHING = ENCHANTMENTS.register("leeching", () -> new LeechingEnchantment());
    public static RegistryObject<PainCycleEnchantment> PAIN_CYCLE = ENCHANTMENTS.register("pain_cycle", () -> new PainCycleEnchantment());
    public static RegistryObject<ProspectorEnchantment> PROSPECTOR = ENCHANTMENTS.register("prospector", () -> new ProspectorEnchantment());
    public static RegistryObject<RadianceEnchantment> RADIANCE = ENCHANTMENTS.register("radiance", () -> new RadianceEnchantment());
    public static RegistryObject<RampagingEnchantment> RAMPAGING = ENCHANTMENTS.register("rampaging", () -> new RampagingEnchantment());
    public static RegistryObject<RushdownEnchantment> RUSHDOWN = ENCHANTMENTS.register("rushdown", () -> new RushdownEnchantment());
    public static RegistryObject<ShockwaveEnchantment> SHOCKWAVE = ENCHANTMENTS.register("shockwave", () -> new ShockwaveEnchantment());
    public static RegistryObject<SoulSiphonEnchantment> SOUL_SIPHON = ENCHANTMENTS.register("soul_siphon", () -> new SoulSiphonEnchantment());
    public static RegistryObject<StunningEnchantment> STUNNING = ENCHANTMENTS.register("stunning", () -> new StunningEnchantment());
    public static RegistryObject<SwirlingEnchantment> SWIRLING = ENCHANTMENTS.register("swirling", () -> new SwirlingEnchantment());
    public static RegistryObject<ThunderingEnchantment> THUNDERING = ENCHANTMENTS.register("thundering", () -> new ThunderingEnchantment());
    public static RegistryObject<WeakeningEnchantment> WEAKENING = ENCHANTMENTS.register("weakening", () -> new WeakeningEnchantment());
    public static RegistryObject<AccelerateEnchantment> ACCELERATE = ENCHANTMENTS.register("accelerate", () -> new AccelerateEnchantment());
    public static RegistryObject<BonusShotEnchantment> BONUS_SHOT = ENCHANTMENTS.register("bonus_shot", () -> new BonusShotEnchantment());
    public static RegistryObject<BurstBowstringEnchantment> BURST_BOWSTRING = ENCHANTMENTS.register("burst_bowstring", () -> new BurstBowstringEnchantment());
    public static RegistryObject<ChainReactionEnchantment> CHAIN_REACTION = ENCHANTMENTS.register("chain_reaction", () -> new ChainReactionEnchantment());
    public static RegistryObject<CooldownShotEnchantment> COOLDOWN_SHOT = ENCHANTMENTS.register("cooldown_shot", () -> new CooldownShotEnchantment());
    public static RegistryObject<FuseShotEnchantment> FUSE_SHOT = ENCHANTMENTS.register("fuse_shot", () -> new FuseShotEnchantment());
    public static RegistryObject<GrowingEnchantment> GROWING = ENCHANTMENTS.register("growing", () -> new GrowingEnchantment());
    public static RegistryObject<OverchargeEnchantment> OVERCHARGE = ENCHANTMENTS.register("overcharge", () -> new OverchargeEnchantment());
    public static RegistryObject<ReplenishEnchantment> REPLENISH = ENCHANTMENTS.register("replenish", () -> new ReplenishEnchantment());
    public static RegistryObject<RadianceShotEnchantment> RADIANCE_SHOT = ENCHANTMENTS.register("radiance_shot", () -> new RadianceShotEnchantment());
    public static RegistryObject<RicochetEnchantment> RICOCHET = ENCHANTMENTS.register("ricochet", () -> new RicochetEnchantment());
    public static RegistryObject<RollChargeEnchantment> ROLL_CHARGE = ENCHANTMENTS.register("roll_charge", () -> new RollChargeEnchantment());
    public static RegistryObject<ShockWebEnchantment> SHOCK_WEB = ENCHANTMENTS.register("shock_web", () -> new ShockWebEnchantment());
    public static RegistryObject<SuperchargeEnchantment> SUPERCHARGE = ENCHANTMENTS.register("supercharge", () -> new SuperchargeEnchantment());
    public static RegistryObject<TempoTheftEnchantment> TEMPO_THEFT = ENCHANTMENTS.register("tempo_theft", () -> new TempoTheftEnchantment());
    public static RegistryObject<FreezingShotEnchantment> FREEZING_SHOT = ENCHANTMENTS.register("freezing_shot", () -> new FreezingShotEnchantment());
    public static RegistryObject<GaleShotEnchantment> GALE_SHOT = ENCHANTMENTS.register("gale_shot", () -> new GaleShotEnchantment());
    public static RegistryObject<GravityShotEnchantment> GRAVITY_SHOT = ENCHANTMENTS.register("gravity_shot", () -> new GravityShotEnchantment());
    public static RegistryObject<ExplodingShotEnchantment> EXPLODING_SHOT = ENCHANTMENTS.register("exploding_shot", () -> new ExplodingShotEnchantment());
    public static RegistryObject<HarpoonShotEnchantment> HARPOON_SHOT = ENCHANTMENTS.register("harpoon_shot", () -> new HarpoonShotEnchantment());
    public static RegistryObject<VelocityEnchantment> VELOCITY = ENCHANTMENTS.register("velocity", () -> new VelocityEnchantment());
    public static RegistryObject<WildRageEnchantment> WILD_RAGE = ENCHANTMENTS.register("wild_rage", () -> new WildRageEnchantment());
    public static RegistryObject<AcrobatEnchantment> ACROBAT = ENCHANTMENTS.register("acrobat", () -> new AcrobatEnchantment());
    public static RegistryObject<AltruisticEnchantment> ALTRUISTIC = ENCHANTMENTS.register("altruistic", () -> new AltruisticEnchantment());
    public static RegistryObject<BagOfSoulsEnchantment> BAG_OF_SOULS = ENCHANTMENTS.register("bag_of_souls", () -> new BagOfSoulsEnchantment());
    public static RegistryObject<BurningEnchantment> BURNING = ENCHANTMENTS.register("burning", () -> new BurningEnchantment());
    public static RegistryObject<BeastBossEnchantment> BEAST_BOSS = ENCHANTMENTS.register("beast_boss", () -> new BeastBossEnchantment());
    public static RegistryObject<BeastBurstEnchantment> BEAST_BURST = ENCHANTMENTS.register("beast_burst", () -> new BeastBurstEnchantment());
    public static RegistryObject<BeastSurgeEnchantment> BEAST_SURGE = ENCHANTMENTS.register("beast_surge", () -> new BeastSurgeEnchantment());
    public static RegistryObject<ChillingEnchantment> CHILLING = ENCHANTMENTS.register("chilling", () -> new ChillingEnchantment());
    public static RegistryObject<SpeedAuraEnchantment> SPEED_AURA = ENCHANTMENTS.register("speed_aura", () -> new SpeedAuraEnchantment());
    public static RegistryObject<MeleeAuraEnchantment> MELEE_AURA = ENCHANTMENTS.register("melee_aura", () -> new MeleeAuraEnchantment());
    public static RegistryObject<PotionAuraEnchantment> POTION_AURA = ENCHANTMENTS.register("potion_aura", () -> new PotionAuraEnchantment());
    public static RegistryObject<LifeStealAuraEnchantment> LIFE_STEAL_AURA = ENCHANTMENTS.register("life_steal_aura", () -> new LifeStealAuraEnchantment());
    public static RegistryObject<CooldownEnchantment> COOLDOWN = ENCHANTMENTS.register("cooldown", () -> new CooldownEnchantment());
    public static RegistryObject<CowardiceEnchantment> COWARDICE = ENCHANTMENTS.register("cowardice", () -> new CowardiceEnchantment());
    public static RegistryObject<DeathBarterEnchantment> DEATH_BARTER = ENCHANTMENTS.register("death_barter", () -> new DeathBarterEnchantment());
    public static RegistryObject<DeflectEnchantment> DEFLECT = ENCHANTMENTS.register("deflect", () -> new DeflectEnchantment());
    public static RegistryObject<ElectrifiedEnchantment> ELECTRIFIED = ENCHANTMENTS.register("electrified", () -> new ElectrifiedEnchantment());
    public static RegistryObject<ExplorerEnchantment> EXPLORER = ENCHANTMENTS.register("explorer", () -> new ExplorerEnchantment());
    public static RegistryObject<FinalShoutEnchantment> FINAL_SHOUT = ENCHANTMENTS.register("final_shout", () -> new FinalShoutEnchantment());
    public static RegistryObject<FireFocusEnchantment> FIRE_FOCUS = ENCHANTMENTS.register("fire_focus", () -> new FireFocusEnchantment());
    public static RegistryObject<FireTrailEnchantment> FIRE_TRAIL = ENCHANTMENTS.register("fire_trail", () -> new FireTrailEnchantment());
    public static RegistryObject<FoodReservesEnchantment> FOOD_RESERVES = ENCHANTMENTS.register("food_reserves", () -> new FoodReservesEnchantment());
    public static RegistryObject<FortuneOfTheSeaEnchantment> FORTUNE_OF_THE_SEA = ENCHANTMENTS.register("fortune_of_the_sea", () -> new FortuneOfTheSeaEnchantment());
    public static RegistryObject<FrenziedEnchantment> FRENZIED = ENCHANTMENTS.register("frenzied", () -> new FrenziedEnchantment());
    public static RegistryObject<GravityPulseEnchantment> GRAVITY_PULSE = ENCHANTMENTS.register("gravity_pulse", () -> new GravityPulseEnchantment());
    public static RegistryObject<HealthSynergyEnchantment> HEALTH_SYNERGY = ENCHANTMENTS.register("health_synergy", () -> new HealthSynergyEnchantment());
    public static RegistryObject<LifeBoostEnchantment> LIFE_BOOST = ENCHANTMENTS.register("life_boost", () -> new LifeBoostEnchantment());
    public static RegistryObject<LightningFocusEnchantment> LIGHTNING_FOCUS = ENCHANTMENTS.register("lightning_focus", () -> new LightningFocusEnchantment());
    public static RegistryObject<LuckyExplorerEnchantment> LUCKY_EXPLORER = ENCHANTMENTS.register("lucky_explorer", () -> new LuckyExplorerEnchantment());
    public static RegistryObject<MultiRollEnchantment> MULTI_ROLL = ENCHANTMENTS.register("multi_roll", () -> new MultiRollEnchantment());
    public static RegistryObject<PoisonFocusEnchantment> POISON_FOCUS = ENCHANTMENTS.register("poison_focus", () -> new PoisonFocusEnchantment());
    public static RegistryObject<PotionBarrierEnchantment> POTION_BARRIER = ENCHANTMENTS.register("potion_barrier", () -> new PotionBarrierEnchantment());
    public static RegistryObject<RecklessEnchantment> RECKLESS = ENCHANTMENTS.register("reckless", () -> new RecklessEnchantment());
    public static RegistryObject<RecyclerEnchantment> RECYCLER = ENCHANTMENTS.register("recycler", () -> new RecyclerEnchantment());
    public static RegistryObject<RushEnchantment> RUSH = ENCHANTMENTS.register("rush", () -> new RushEnchantment());
    public static RegistryObject<SoulFocusEnchantment> SOUL_FOCUS = ENCHANTMENTS.register("soul_focus", () -> new SoulFocusEnchantment());
    public static RegistryObject<SnowballEnchantment> SNOWBALL = ENCHANTMENTS.register("snowball", () -> new SnowballEnchantment());
    public static RegistryObject<SpeedSynergyEnchantment> SPEED_SYNERGY = ENCHANTMENTS.register("speed_synergy", () -> new SpeedSynergyEnchantment());
    public static RegistryObject<SurpriseGiftEnchantment> SURPRISE_GIFT = ENCHANTMENTS.register("surprise_gift", () -> new SurpriseGiftEnchantment());
    public static RegistryObject<SwiftfootedEnchantment> SWIFTFOOTED = ENCHANTMENTS.register("swiftfooted", () -> new SwiftfootedEnchantment());
    public static RegistryObject<TumblebeeEnchantment> TUMBLEBEE = ENCHANTMENTS.register("tumblebee", () -> new TumblebeeEnchantment());
    public static RegistryObject<OpulentShieldEnchantment> OPULENT_SHIELD = ENCHANTMENTS.register("opulent_shield", () -> new OpulentShieldEnchantment());
    public static RegistryObject<ArrowHoarderEnchantment> ARROW_HOARDER = ENCHANTMENTS.register("arrow_hoarder", () -> new ArrowHoarderEnchantment());
    public static RegistryObject<VoidDodgeEnchantment> VOID_DODGE = ENCHANTMENTS.register("void_dodge", () -> new VoidDodgeEnchantment());
    public static RegistryObject<DodgeEnchantment> DODGE = ENCHANTMENTS.register("dodge", () -> new DodgeEnchantment());
    public static RegistryObject<BeehiveEnchantment> BEEHIVE = ENCHANTMENTS.register("beehive", () -> new BeehiveEnchantment());

}
